### PR TITLE
Fix issue with character covariates

### LINKED ISSUE #293: Character covariate leads to error in `impute()` after that `draws()` ran smoothly
If we include a categorical covariate in the imputation model as a `character` instead of as a `factor`, `draws()` runs smoothly but `impute()` leads to the following error:

```
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels
```
The error seems to come from a call to `as_model_df()`. Indeed, for a single subject a baseline categorical covariate takes only one value (e.g. sex "F") which leads to the failure of the build of the design matrix. 

Reproducible example:

```
library(rbmi)
library(dplyr)

data("antidepressant_data")
dat <- antidepressant_data %>% 
    mutate(GENDER = as.character(GENDER))

## Use expand_locf to add the dropped observations into the dataset
dat <- expand_locf(
    dat,
    PATIENT = levels(dat$PATIENT), # expand by PATIENT and VISIT 
    VISIT = levels(dat$VISIT),
    vars = c("BASVAL", "THERAPY", "GENDER"), # fill with LOCF BASVAL and THERAPY
    group = c("PATIENT"),
    order = c("PATIENT", "THERAPY")
)

# create data_ice and set the imputation strategy to JR for
# each patient with at least one missing observation
dat_ice <- dat %>% 
    arrange(PATIENT, VISIT) %>% 
    filter(is.na(CHANGE)) %>% 
    group_by(PATIENT) %>% 
    slice(1) %>%
    ungroup() %>% 
    select(PATIENT, VISIT) %>% 
    mutate(strategy = "JR")

# In this dataset, subject 3618 has an intermittent missing values which does not correspond
# to a study drug discontinuation. We therefore remove this subject from `dat_ice`. 
# (In the later imputation step, it will automatically be imputed under the default MAR assumption.)
dat_ice <- dat_ice[-which(dat_ice$PATIENT == 3618),] 
dat_ice

vars <- set_vars(
    outcome = "CHANGE",
    visit = "VISIT",
    subjid = "PATIENT",
    group = "THERAPY",
    covariates = c("BASVAL*VISIT", "THERAPY*VISIT", "GENDER")
)

method <- method_bayes(
    burn_in = 200,
    burn_between = 5,
    n_samples = 15
)

set.seed(987)
drawObj <- draws(
    data = dat,
    data_ice = dat_ice,
    vars = vars,
    method = method,
    quiet = TRUE
)

imputeObj <- impute(
    drawObj,
    references = c("DRUG" = "PLACEBO", "PLACEBO" = "PLACEBO")
)
```

### PR DESCRIPTION
**Pull request by gowerc**
Closes #293

### CODE REVIEW

File: R/draws.R [hunk 1]
```diff
@@ -82,6 +83,11 @@
 #' observations to be included in the model as part of the response variable then these should be removed in advance
 #' from the outcome variable in `data`. At the same time if you want to include the baseline outcome as covariate in
 #' the model, then this should be included as a separate column of `data` (as any other covariate).
+#' 
+#' Character covariates will be explicitly
+#' cast to factors. If you use a custom analysis function that requires specific reference
+#' levels for the character covariates (for example for LSmeans) then you are advised
```
Comment (nociale) [inline R/draws.R:89]:
```suggestion
#' levels for the character covariates (for example for least square means computation) then you are advised
```

File: tests/testthat/test-misc.R [hunk 2]
```diff
@@ -89,5 +89,74 @@ test_that("rbmi can handle 'grouped' dplyr data", {
 
 
 
+test_that("`rbmi` can handle character data", {
+    dat <- simulate_data(100) %>%
```
Comment (nociale) [inline tests/testthat/test-misc.R:93]: I guess this will need to ba changed to `simulate_test_data`?

**Comment by nociale** [comment]
Just small comments.

**Review by nociale — APPROVED** [review]
