### PR TITLE
Ensure reproducible if using model cache

### LINKED ISSUE #469: rbmi 1.3.1: first fit after compiling model not reproducible with subsequent fits
**Describe the bug**
When fitting the rbmi model for the first time and the model is initially compiled, the results differ from subsequent fits. Is it possible the compilation process has some side effects (e.g., changing the seed)?

Update: it does indeed look like the seed that is set is different.

**To Reproduce**
``` r
library(rbmi)
options("rbmi.cache_dir" = tempdir(check = TRUE))
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union


data("antidepressant_data")
dat <- antidepressant_data
dat <- expand_locf(
  dat,
  PATIENT = levels(dat$PATIENT), # expand by PATIENT and VISIT
  VISIT = levels(dat$VISIT),
  vars = c("BASVAL", "THERAPY"), # fill with LOCF BASVAL and THERAPY
  group = c("PATIENT"),
  order = c("PATIENT", "VISIT")
)
dat_ice <- dat |>
  arrange(PATIENT, VISIT) |>
  filter(is.na(CHANGE)) |>
  group_by(PATIENT) |>
  slice(1) |>
  ungroup() |>
  select(PATIENT, VISIT) |>
  mutate(strategy = "JR")
dat_ice <- dat_ice[-which(dat_ice$PATIENT == 3618), ]
vars <- set_vars(
  outcome = "CHANGE",
  visit = "VISIT",
  subjid = "PATIENT",
  group = "THERAPY",
  covariates = c("BASVAL*VISIT", "THERAPY*VISIT")
)
method <- method_bayes(
  burn_in = 100,
  burn_between = 1,
  n_samples = 200
)

sample_and_compute_poolobj <- function(dat, dat_ice, vars, method){
  trace(what = rbmi:::fit_mcmc, at = 12, tracer = quote(print(sampling_args$seed)))
  drawObj <- draws(
    data = dat,
    data_ice = dat_ice,
    vars = vars,
    method = method,
    quiet = TRUE
  )
  
  # Impute the data
  imputeObj <- impute(
    drawObj,
    references = c("DRUG" = "PLACEBO", "PLACEBO" = "PLACEBO")
  )
  
  # Fit the analysis model on each imputed dataset
  anaObj <- analyse(
    imputeObj,
    ancova,
    vars = set_vars(
      subjid = "PATIENT",
      outcome = "CHANGE",
      visit = "VISIT",
      group = "THERAPY",
      covariates = c("BASVAL")
    )
  )
  
  # Apply a delta adjustment
  
  # Add a delta-value of 5 to all imputed values (i.e. those values
  # which were missing in the original dataset) in the drug arm.
  delta_df <- delta_template(imputeObj) %>%
    as_tibble() %>%
    mutate(delta = if_else(THERAPY == "DRUG" & is_missing , 5, 0)) %>%
    select(PATIENT, VISIT, delta)
  
  # Repeat the analyses with the adjusted values
  anaObj_delta <- analyse(
    imputeObj,
    ancova,
    delta = delta_df,
    vars = set_vars(
      subjid = "PATIENT",
      outcome = "CHANGE",
      visit = "VISIT",
      group = "THERAPY",
      covariates = c("BASVAL")
    )
  )
  
  # Pool the results
  poolObj <- pool(
    anaObj,
    conf.level = 0.95,
    alternative = "two.sided"
  )
  poolObj
}
set.seed(123)
poolObj1 <- sample_and_compute_poolobj(dat, dat_ice, vars, method)
#> Tracing function "fit_mcmc" in package "rbmi (not-exported)"
#> Tracing fit_mcmc(designmat = model_df_scaled[, -1, drop = FALSE], outcome = model_df_scaled[,  .... step 12 
#> [1] 1673048412
#> Warning: The Effective Sample Size is below 40% for 8 parameters. Please
#> consider increasing burn-in and/or burn-between, or the number of samples
set.seed(123)
poolObj2 <- sample_and_compute_poolobj(dat, dat_ice, vars, method)
#> Tracing function "fit_mcmc" in package "rbmi (not-exported)"
#> recompiling to avoid crashing R session
#> Tracing fit_mcmc(designmat = model_df_scaled[, -1, drop = FALSE], outcome = model_df_scaled[,  .... step 12 
#> [1] 1235143119
#> Warning: The Effective Sample Size is below 40% for 15 parameters. Please
#> consider increasing burn-in and/or burn-between, or the number of samples
set.seed(123)
poolObj3 <- sample_and_compute_poolobj(dat, dat_ice, vars, method)
#> Tracing function "fit_mcmc" in package "rbmi (not-exported)"
#> recompiling to avoid crashing R session
#> Tracing fit_mcmc(designmat = model_df_scaled[, -1, drop = FALSE], outcome = model_df_scaled[,  .... step 12 
#> [1] 1235143119
#> Warning: The Effective Sample Size is below 40% for 15 parameters. Please
#> consider increasing burn-in and/or burn-between, or the number of samples

print(list(
  cache_dir = getOption("rbmi.cache_dir"),
  poolObj1 = digest::digest(poolObj1),
  poolObj2 = digest::digest(poolObj2),
  poolObj3 = digest::digest(poolObj3)
))
#> $cache_dir
#> [1] "/var/folders/cd/0t58mmhj4nzgsn343pkx2lc80000gn/T//Rtmp8DfeuY"
#> 
#> $poolObj1
#> [1] "fc1a471c915b5a421c845c1bd201ec48"
#> 
#> $poolObj2
#> [1] "7570c9b6c00bc45cdde9b4b07ca82d67"
#> 
#> $poolObj3
#> [1] "7570c9b6c00bc45cdde9b4b07ca82d67"
```

<sup>Created on 2025-01-06 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
  
  <details style="margin-bottom:10px;">
  <summary>
  Session info
</summary>
  
  ``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.4.1 (2024-06-14)
#>  os       macOS 15.2
#>  system   aarch64, darwin20
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       Europe/Zurich
#>  date     2025-01-06
#>  pandoc   3.2 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/aarch64/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package      * version  date (UTC) lib source
#>  assertthat     0.2.1    2019-03-21 [1] CRAN (R 4.4.0)
#>  backports      1.5.0    2024-05-23 [1] CRAN (R 4.4.0)
#>  callr          3.7.6    2024-03-25 [1] CRAN (R 4.4.0)
#>  checkmate      2.3.2    2024-07-29 [1] CRAN (R 4.4.0)
#>  cli            3.6.3    2024-06-21 [1] CRAN (R 4.4.0)
#>  codetools      0.2-20   2024-03-31 [1] CRAN (R 4.4.1)
#>  colorspace     2.1-1    2024-07-26 [1] CRAN (R 4.4.0)
#>  curl           6.0.1    2024-11-14 [1] CRAN (R 4.4.1)
#>  digest         0.6.37   2024-08-19 [1] CRAN (R 4.4.1)
#>  dplyr        * 1.1.4    2023-11-17 [1] CRAN (R 4.4.0)
#>  evaluate       1.0.1    2024-10-10 [1] CRAN (R 4.4.1)
#>  fansi          1.0.6    2023-12-08 [1] CRAN (R 4.4.0)
#>  fastmap        1.2.0    2024-05-15 [1] CRAN (R 4.4.0)
#>  fs             1.6.5    2024-10-30 [1] CRAN (R 4.4.1)
#>  generics       0.1.3    2022-07-05 [1] CRAN (R 4.4.0)
#>  ggplot2        3.5.1    2024-04-23 [1] CRAN (R 4.4.0)
#>  glue           1.8.0    2024-09-30 [1] CRAN (R 4.4.1)
#>  gridExtra      2.3      2017-09-09 [1] CRAN (R 4.4.0)
#>  gtable         0.3.6    2024-10-25 [1] CRAN (R 4.4.1)
#>  htmltools      0.5.8.1  2024-04-04 [1] CRAN (R 4.4.0)
#>  inline         0.3.20   2024-11-10 [1] CRAN (R 4.4.1)
#>  jsonlite       1.8.9    2024-09-20 [1] CRAN (R 4.4.1)
#>  knitr          1.49     2024-11-08 [1] CRAN (R 4.4.1)
#>  lattice        0.22-6   2024-03-20 [1] CRAN (R 4.4.1)
#>  lifecycle      1.0.4    2023-11-07 [1] CRAN (R 4.4.0)
#>  loo            2.8.0    2024-07-03 [1] CRAN (R 4.4.0)
#>  magrittr       2.0.3    2022-03-30 [1] CRAN (R 4.4.0)
#>  Matrix         1.7-1    2024-10-18 [1] CRAN (R 4.4.1)
#>  matrixStats    1.4.1    2024-09-08 [1] CRAN (R 4.4.1)
#>  mmrm           0.3.14   2024-09-27 [1] CRAN (R 4.4.1)
#>  munsell        0.5.1    2024-04-01 [1] CRAN (R 4.4.0)
#>  nlme           3.1-166  2024-08-14 [1] CRAN (R 4.4.0)
#>  pillar         1.9.0    2023-03-22 [1] CRAN (R 4.4.0)
#>  pkgbuild       1.4.5    2024-10-28 [1] CRAN (R 4.4.1)
#>  pkgconfig      2.0.3    2019-09-22 [1] CRAN (R 4.4.0)
#>  processx       3.8.4    2024-03-16 [1] CRAN (R 4.4.0)
#>  ps             1.8.1    2024-10-28 [1] CRAN (R 4.4.1)
#>  QuickJSR       1.4.0    2024-10-01 [1] CRAN (R 4.4.1)
#>  R6             2.5.1    2021-08-19 [1] CRAN (R 4.4.0)
#>  rbibutils      2.3      2024-10-04 [1] CRAN (R 4.4.1)
#>  rbmi         * 1.3.1    2024-12-11 [1] CRAN (R 4.4.1)
#>  Rcpp           1.0.13-1 2024-11-02 [1] CRAN (R 4.4.1)
#>  RcppParallel   5.1.9    2024-08-19 [1] CRAN (R 4.4.1)
#>  Rdpack         2.6.2    2024-11-15 [1] CRAN (R 4.4.1)
#>  reprex         2.1.1    2024-07-06 [1] CRAN (R 4.4.0)
#>  rlang          1.1.4    2024-06-04 [1] CRAN (R 4.4.0)
#>  rmarkdown      2.29     2024-11-04 [1] CRAN (R 4.4.1)
#>  rstan          2.32.6   2024-03-05 [1] CRAN (R 4.4.0)
#>  rstudioapi     0.17.1   2024-10-22 [1] CRAN (R 4.4.1)
#>  scales         1.3.0    2023-11-28 [1] CRAN (R 4.4.0)
#>  sessioninfo    1.2.2    2021-12-06 [1] CRAN (R 4.4.0)
#>  StanHeaders    2.32.10  2024-07-15 [1] CRAN (R 4.4.0)
#>  stringi        1.8.4    2024-05-06 [1] CRAN (R 4.4.0)
#>  stringr        1.5.1    2023-11-14 [1] CRAN (R 4.4.0)
#>  tibble         3.2.1    2023-03-20 [1] CRAN (R 4.4.0)
#>  tidyselect     1.2.1    2024-03-11 [1] CRAN (R 4.4.0)
#>  TMB            1.9.15   2024-09-09 [1] CRAN (R 4.4.1)
#>  utf8           1.2.4    2023-10-22 [1] CRAN (R 4.4.0)
#>  V8             6.0.0    2024-10-12 [1] CRAN (R 4.4.1)
#>  vctrs          0.6.5    2023-12-01 [1] CRAN (R 4.4.0)
#>  withr          3.0.2    2024-10-28 [1] CRAN (R 4.4.1)
#>  xfun           0.49     2024-10-31 [1] CRAN (R 4.4.1)
#>  yaml           2.3.10   2024-07-26 [1] CRAN (R 4.4.0)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Screenshots**

**Environment (please complete the following information):**
 - OS: Multiple
 - R version: 4.3.1, 4.4.1
 - rbmi version: 1.3.1

### PR DESCRIPTION
**Pull request by gowerc**
Closes #469 

FYI @luwidmer

### CODE REVIEW

**Comment by luwidmer** [comment]
@gowerc doesn't .Random.seed always exist? At least I get

```r
Restarting R session...

> exists(".Random.seed")
[1] TRUE
> ls()
character(0)
> .Random.seed <<- .Random.seed
> ls()
character(0)
> exists(".Random.seed")
[1] TRUE
```

File: R/utilities.R [hunk 1]
```diff
@@ -556,11 +556,25 @@ clear_model_cache <- function(cache_dir = getOption("rbmi.cache_dir")) {
...
+    # Compiling Stan models updates the current seed state. This can lead to
+    # non-reproducibility as compiling is conditional on wether there is a cached
+    # model available or not. Thus we save the current seed state and restore it
+    # at the end of this function so that it is in the same state regardless of
+    # whether the model was compiled or not.
+    # See https://github.com/insightsengineering/rbmi/issues/469
+    # Note that .Random.seed is only set if the seed has been set or if a random number
+    # has been generated.
+    if (exists(".Random.seed")) {
+        current_seed_state <- .Random.seed
```
Comment (gravesti) [inline R/utilities.R:575]: @gowerc 
To be a bit more robust, eg in case the function has an error, you can do something like

```suggestion
        current_seed_state <- .Random.seed
        on.exit(suspendInterrupts(
            assign(".Random.seed", value = current_seed_state, envir = globalenv(), inherits = FALSE)
        ))
```

In another package we have 
```r
    # Make sure to leave '.Random.seed' as-is on exit
    old_seed <- globalenv()$.Random.seed
    on.exit(suspendInterrupts(set_random_seed(old_seed)))
```
with the function
```r
# Restore the RNG back to a previous state using the global .Random.seed
set_random_seed <- function(old_seed) {
  if (is.null(old_seed)) {
    rm(".Random.seed", envir = globalenv(), inherits = FALSE)
  } else {
    assign(".Random.seed", value = old_seed, envir = globalenv(), inherits = FALSE)
  }
```

File: R/utilities.R [hunk 2]
```diff
@@ -580,11 +594,16 @@ get_stan_model <- function() {
...
+    model <- rstan::stan_model(
         file = model_file,
         auto_write = TRUE,
         model_name = "rbmi_mmrm"
     )
+
+    if (exists("current_seed_state")) {
+        .Random.seed <- current_seed_state
+    }
+    return(model)
```
Comment (gravesti) [inline R/utilities.R:606]: These changes wouldn't be needed if you use `on.exit()`

File: R/utilities.R (hunk 1 above)
Comment (luwidmer) [reply R/utilities.R:575]: As I understand it, suspends user interrupts (Ctrl+C, ...) but also timing limits - see errors.c in the R source code: https://github.com/wch/r-source/blob/e7772053c2087dedec9351c80b82e3ec2b541f86/src/main/errors.c#L141

**Review by gravesti — APPROVED** [review]
Looks good @gowerc
